import type { Metadata } from "next";
import localFont from "next/font/local";

import { ThirdwebProvider } from "@/components";

import "./globals.css";
import StateProvider from "@/utils/context/StateProvider";

const Chillax = localFont({
  display: "swap",
  src: [
    {
      path: "../font/Chillax-Extralight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../font/Chillax-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../font/Chillax-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/Chillax-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/Chillax-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../font/Chillax-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThirdwebProvider>
      <StateProvider>
        <html lang="en">
          <body className={Chillax.className}>{children}</body>
        </html>
      </StateProvider>
    </ThirdwebProvider>
  );
}
